### ISSUE TITLE
Confirm that config file generation works in a multi-app server environment

### ISSUE THREAD

**Issue by reagent** [vigetlabs/viget-deployment#6]
Scenario

* App server 1 has been set up and has a local `config/database.yml` file
* App server 2 has been set up and does not have a local `config/database.yml` file
* Running `cap deploy` should prompt for database credentials and write those to the config file on both servers
* A subsequent run of `cap deploy` should not prompt for database configuration

See [this SO post](http://stackoverflow.com/a/15436165) for more information on how this should work.

**Comment by yaychris** [comment]
I can confirm that this works. Closing.
